#  _____                    _  __ ____  
# | ____| __ _  ___  _   _ | |/ /| __ ) 
# |  _|  / _` |/ __|| | | || ' / |  _ \ 
# | |___| (_| |\__ \| |_| || . \ | |_) |
# |_____|\__,_||___/ \__, ||_|\_\|____/ 
#                   |___/              
#This plugin was made by FAN. All right reserved

#0 = default KnockBack
KnockBack: 0